// src/components/properties/RichtextProperty.vue
<template>
  <div v-if="mode === 'browse'">
      <div v-html="view.value"></div>
    </div>
  <div v-else-if="mode === 'link'">
    <div class="label textarea"><i class="fa fa-comment"></i><span>{{ view.title }}</span></div>
  </div>
  <div v-else-if="mode === 'search'">
    <div class="label textarea"><i class="fa fa-comment"></i><span>{{ view.title }}</span></div>
    <div><input type="text" :value="view.value" placeholder=""></div>
  </div>
</template>

<script>
export default {
  name: 'richtext-property',
  props: ['className', 'mode', 'view', 'model']
}
</script>

// src/components/properties/richtext-property/richtext-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'richtext-property',
  templateUrl: './richtext-property.component.html',
  styleUrls: ['./richtext-property.component.css']
})
export class RichtextPropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;
  @Output() onRichtextSubmit = new EventEmitter;

  constructor() { }

  ngOnInit() {
  }

  setModel(content) {
    this.model[this.view.name].value = content;
  }

  onSubmit() {
    this.onRichtextSubmit.emit();
  }
}
<div *ngIf="mode == 'edit'">
    <label>{{view.title}}:</label><span attr.name="{{view.name}}" class="error"></span><br>
    <tinymce [elementId]="'richtext'" [value]="view.value" (onEditorKeyup)="setModel($event)" (onTinymceSubmit)="onSubmit()"></tinymce>
</div>
<div *ngIf="mode == 'browse'">
    {{view.value}}
</div>
<div *ngIf="mode == 'link'">
    <div class="label textarea"><span class="glyphicons glyphicons-comments"></span><span>{{view.title}}</span></div>
</div>
<div *ngIf="mode == 'search'">
    <div class="label textarea"><span class="glyphicons glyphicons-comments"></span><span>{{view.title}}</span></div>
    <div><input type="text" value="{{view.value}}" placeholder=""></div>
</div>
