// src/components/properties/DateProperty.vue
<template>
  <div v-if="mode === 'browse'">
    <div class="date">{{ view.value | date('DD.MM.YYYY') }}</div>
  </div>
  <div v-else-if="mode === 'edit'">
    <div v-if="view.readonly && view.value">
      <label>{{ view.title }}:</label> {{ view.value | date('DD.MM.YYYY') }}, {{ view.value | date('HH:mm:ss') }}
    </div>
    <div v-else-if="view.readonly && ! view.value">
      <label>{{ view.title }}:</label> Не определено
    </div>
    <div v-else>
      <label>{{ view.title }}:</label><span :name="view.name" :label="view.title" class="error"></span><br>
      <datepicker :name="view.name" v-on:input="setDate(arguments[0])" :value="value" v-bind:monday-first="true" format="dd.MM.yyyy" input-class="date" language="ru"></datepicker>
    </div>
  </div>
  <div v-else-if="mode === 'link'">
    <div class="label date"><i class="fa fa-calendar"></i><span>{{ view.title }}</span></div>
  </div>
  <div v-else-if="mode === 'search'">
    <div class="label date"><i class="fa fa-calendar"></i><span>{{ view.title }}</span></div>
    <div>
      <datepicker v-bind:monday-first="true" format="dd.MM.yyyy" input-class="date" language="ru" :value="view.value" placeholder="От"></datepicker> &mdash;
      <datepicker v-bind:monday-first="true" format="dd.MM.yyyy" input-class="date" language="ru" :value="view.value" placeholder="До"></datepicker>
    </div>
  </div>
</template>

<script>
import moment from 'moment'
import Datepicker from 'vuejs-datepicker'

export default {
  name: 'date-property',
  components: { Datepicker },
  props: ['className', 'mode', 'view', 'model'],
  data () {
    return {
      value: null
    }
  },
  computed: {
    date () {
      return this.view.value ? moment(this.view.value).format('YYYY-MM-DD') : null
    }
  },
  mounted () {
    this.value = this.date

    this.$emit('update', {value: this.value})
  },
  methods: {
    setDate (value) {
      this.value = value ? moment(value).format('YYYY-MM-DD') : null
      this.$emit('update', {value: this.value})
    }
  }
}
</script>

<style>
input[type="text"].date {
  width: 5rem;
  border-color: #999;
}
</style>

// src/components/properties/date-property/date-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import '../../../assets/js/calendarview/jquery.calendar.js';

declare var jQuery: any;

@Component({
  selector: 'date-property',
  templateUrl: './date-property.component.html',
  styleUrls: ['./date-property.component.css']
})
export class DatePropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;
  @Input() date: string;

  constructor() { }

  ngOnInit() {
    this.setDate();
  }

  ngAfterViewInit() {
    let self = this;

    jQuery('#'+this.view.name+'_date').val(this.date);

    jQuery('#'+this.view.name+'_date').calendar({
      dateFormat: '%Y-%m-%d',
      selectHandler: function() {
        self.date = this.date.print(this.dateFormat);
        self.setDate();
      }
    });
  }

  setDate() {
    try {
      let date = new Date(this.date);

      this.model[this.view.name].value = date.toISOString();
    } catch (err) {}
  }
}

<div *ngIf="mode == 'edit'">
    <div *ngIf="view.readonly">
        <label>{{view.title}}:</label> {{view.value | date: 'dd.MM.yyyy'}}
    </div>
    <div *ngIf=" ! view.readonly">
        <label>{{view.title}}:</label><span attr.name="{{view.name}}" class="error"></span><br>
        <input type="text" name="date" [(ngModel)]="date" (ngModelChange)="setDate()" class="date" id="{{view.name}}_date">
    </div>
</div>
<div *ngIf="mode == 'browse'">
     <div *ngIf="view.value">
        {{view.value | date: 'dd.MM.yyyy'}}
    </div>
</div>
<div *ngIf="mode == 'link'">
    <div class="label date"><span class="glyphicons glyphicons-calendar"></span><span>{{view.title}}</span></div>
</div>
<div *ngIf="mode == 'search'">
    <div class="label date"><span class="glyphicons glyphicons-calendar"></span><span>{{view.title}}</span></div>
    <div><input type="text" value="{{view.value}}" class="date" placeholder=""></div>
</div>
