// src/components/properties/DatetimeProperty.vue
<template>
  <div v-if="mode === 'browse'">
    <div class="date">{{ view.value | date('DD.MM.YYYY') }}</div>
    <div class="time">{{ view.value | date('HH:mm:ss') }}</div>
  </div>
  <div v-else-if="mode === 'edit'">
    <div v-if="view.readonly && view.value">
      <label>{{ view.title }}:</label> {{ view.value | date('DD.MM.YYYY') }}, {{ view.value | date('HH:mm:ss') }}
    </div>
    <div v-else-if="view.readonly && ! view.value">
      <label>{{ view.title }}:</label> Не определено
    </div>
    <div v-else>
      <label>{{ view.title }}:</label><span :name="view.name" :label="view.title" class="error"></span><br>
      <datepicker :name="view.name" v-on:input="setDate(arguments[0])" :value="value.date" v-bind:monday-first="true" format="dd.MM.yyyy" input-class="date" language="ru"></datepicker> &nbsp;
      <input type="text" name="hours" v-on:input="setHours($event.target.value)" :value="value.hours" class="time"> :
      <input type="text" name="minutes" v-on:input="setMinutes($event.target.value)" :value="value.minutes" class="time"> :
      <input type="text" name="seconds" v-on:input="setSeconds($event.target.value)" :value="value.seconds" class="time">
    </div>
  </div>
  <div v-else-if="mode === 'link'">
    <div class="label date"><i class="fa fa-calendar"></i><span>{{ view.title }}</span></div>
  </div>
  <div v-else-if="mode === 'search'">
    <div class="label date"><i class="fa fa-calendar"></i><span>{{ view.title }}</span></div>
    <div>
      <datepicker v-bind:monday-first="true" format="dd.MM.yyyy" input-class="date" language="ru" :value="view.value" placeholder="От"></datepicker> &mdash;
      <datepicker v-bind:monday-first="true" format="dd.MM.yyyy" input-class="date" language="ru" :value="view.value" placeholder="До"></datepicker>
    </div>
  </div>
</template>

<script>
import moment from 'moment'
import Datepicker from 'vuejs-datepicker'

export default {
  name: 'datetime-property',
  components: { Datepicker },
  props: ['className', 'mode', 'view', 'model'],
  data () {
    return {
      value: {}
    }
  },
  computed: {
    date () {
      return this.view.value ? moment(this.view.value).format('YYYY-MM-DD') : null
    },
    hours () {
      return this.view.value ? moment(this.view.value).format('HH') : null
    },
    minutes () {
      return this.view.value ? moment(this.view.value).format('mm') : null
    },
    seconds () {
      return this.view.value ? moment(this.view.value).format('ss') : null
    }
  },
  mounted () {
    this.value = {
      date: this.date,
      hours: this.hours,
      minutes: this.minutes,
      seconds: this.seconds
    }

    this.$emit('update', this.value)
  },
  methods: {
    setDate (value) {
      this.value.date = value ? moment(value).format('YYYY-MM-DD') : null
      this.$emit('update', this.value)
    },
    setHours (value) {
      this.value.hours = value
      this.$emit('update', this.value)
    },
    setMinutes (value) {
      this.value.minutes = value
      this.$emit('update', this.value)
    },
    setSeconds (value) {
      this.value.seconds = value
      this.$emit('update', this.value)
    }
  }
}
</script>

<style>
input[type="text"].date {
  width: 5rem;
  border-color: #666;
}

.time {
  font-size: 0.8rem;
  color: #666;
}
</style>

// src/components/properties/datetime-property/datetime-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import '../../../assets/js/calendarview/jquery.calendar.js';

declare var jQuery:any;

@Component({
  selector: 'datetime-property',
  templateUrl: './datetime-property.component.html',
  styleUrls: ['./datetime-property.component.css']
})
export class DatetimePropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;
  @Input() datetime: string;
  @Input() date: string;
  @Input() hours: string;
  @Input() minutes: string;
  @Input() seconds: string;

  constructor() { }

  ngOnInit() {
    this.setDatetime();
  }

  ngAfterViewInit() {
    let self = this;

    jQuery('#'+this.view.name+'_date').val(this.date);

    jQuery('#'+this.view.name+'_date').calendar({
      dateFormat: '%Y-%m-%d',
      selectHandler: function() {
        self.date = this.date.print(this.dateFormat);
        self.setDatetime();
      }
    });
  }

  setDatetime() {
    try {
      this.model[this.view.name] = {
        date: this.date,
        hours: this.hours,
        minutes: this.minutes,
        seconds: this.seconds
      };
    } catch (err) {}
  }
}

<div *ngIf="mode == 'edit'">
    <div *ngIf="view.readonly && view.value">
        <label>{{view.title}}:</label> {{view.value | date: 'dd.MM.yyyy'}}, {{view.value | date: 'HH:mm:ss'}}
    </div>
    <div *ngIf="view.readonly && ! view.value">
        <label>{{view.title}}:</label> Не определено
    </div>
    <div *ngIf=" ! view.readonly">
        <label>{{view.title}}:</label><span attr.name="{{view.name}}" class="error"></span><br>
        <input type="text" name="date" [(ngModel)]="date" (ngModelChange)="setDatetime()" class="date" id="{{view.name}}_date"> &nbsp;&nbsp;&nbsp;
        <input type="text" name="hours" [(ngModel)]="hours" (ngModelChange)="setDatetime()" class="time"> :
        <input type="text" name="minutes" [(ngModel)]="minutes" (ngModelChange)="setDatetime()" class="time"> :
        <input type="text" name="seconds" [(ngModel)]="seconds" (ngModelChange)="setDatetime()" class="time">
    </div>
</div>
<div *ngIf="mode == 'browse'">
    <div *ngIf="view.value">
        {{view.value | date: 'dd.MM.yyyy'}}<br>
        <small>{{view.value | date: 'HH:mm:ss'}}</small>
    </div>
</div>
<div *ngIf="mode == 'link'">
    <div class="label date"><span class="glyphicons glyphicons-calendar"></span><span>{{view.title}}</span></div>
</div>
<div *ngIf="mode == 'search'">
    <div class="label date"><span class="glyphicons glyphicons-calendar"></span><span>{{view.title}}</span></div>
    <div><input type="text" value="{{view.value}}" class="date" placeholder=""></div>
</div>
