// src/components/properties/TextareaProperty.vue
<template>
  <div v-if="mode === 'browse'">
    <div v-html="text"></div>
  </div>
  <div v-else-if="mode === 'edit'">
    <label>{{ view.title }}:</label><span :name="view.name" :label="view.title" class="error"></span><br>
    <textarea :name="view.name" v-on:input="update($event.target.value)" :disabled="view.readonly" :placeholder="view.title" rows="10">{{ view.value }}</textarea>
  </div>
  <div v-else-if="mode === 'link'">
    <div class="label textarea"><i class="fa fa-comment"></i><span>{{ view.title }}</span></div>
  </div>
  <div v-else-if="mode === 'search'">
    <div class="label textarea"><i class="fa fa-comment"></i><span>{{ view.title }}</span></div>
    <div><input type="text" :value="view.value" placeholder=""></div>
  </div>
</template>

<script>
export default {
  name: 'textarea-property',
  props: ['className', 'mode', 'view', 'model'],
  computed: {
    text () {
      return this.view.value ? this.view.value.replace(/\n/g, '<br />') : ''
    }
  },
  mounted () {
    this.update(this.view.value)
  },
  methods: {
    update (value) {
      this.$emit('update', {value: value})
    }
  }
}
</script>

// src/components/properties/textarea-property/textarea-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'textarea-property',
  templateUrl: './textarea-property.component.html',
  styleUrls: ['./textarea-property.component.css']
})
export class TextareaPropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;

  constructor() { }

  ngOnInit() {
  }

  nl2br(text) {
    return text ? text.replace(/\n/g, "<br />") : '';
  }
}
<div *ngIf="mode == 'edit'">
    <label>{{view.title}}:</label><span attr.name="{{view.name}}" class="error"></span><br>
    <textarea name="{{view.name}}" [(ngModel)]="model[view.name].value" [disabled]="view.readonly" placeholder="{{view.title}}" rows="10"></textarea>
</div>
<div *ngIf="mode == 'browse'">
    <div [innerHTML]="nl2br(view.value)"></div>
</div>
<div *ngIf="mode == 'link'">
    <div class="label textarea"><span class="glyphicons glyphicons-comments"></span><span>{{view.title}}</span></div>
</div>
<div *ngIf="mode == 'search'">
    <div class="label textarea"><span class="glyphicons glyphicons-comments"></span><span>{{view.title}}</span></div>
    <div><input type="text" value="{{view.value}}" placeholder=""></div>
</div>
