// src/components/properties/checkbox-property/checkbox-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'checkbox-property',
  templateUrl: './checkbox-property.component.html',
  styleUrls: ['./checkbox-property.component.css']
})
export class CheckboxPropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;

  constructor() { }

  ngOnInit() {
  }

}

<div *ngIf="mode == 'edit'">
    <span attr.name="{{view.name}}" class="error"></span>
    <p><input type="checkbox" name="{{view.name}}" id="{{view.name}}" [(ngModel)]="model[view.name].value" [disabled]="view.readonly" value="1"> <label attr.for="{{view.name}}">{{view.title}}</label></p>
</div>
<div *ngIf="mode == 'browse'">
    <span *ngIf="view.value">Да</span>
    <span *ngIf=" ! view.value" class="grey">Нет</span>
</div>
<div *ngIf="mode == 'link'">
    <div class="label checkbox"><span class="glyphicons glyphicons-ok-2"></span><span>{{view.title}}</span></div>
</div>
<div *ngIf="mode == 'search'">
    <div class="label checkbox"><span class="glyphicons glyphicons-ok-2"></span><span>{{view.title}}</span></div>
    <div></div>
</div>

// src/components/properties/CheckboxProperty.vue
<template>
  <div v-if="mode === 'browse'">
    <div v-if="view.value">Да</div>
    <div v-else class="false">Нет</div>
  </div>
  <div v-else-if="mode === 'edit'">
    <p><input type="checkbox" :name="view.name" :id="view.name" v-on:change="update($event.target.checked)" :checked="view.value" :disabled="view.readonly" value="1"> <label :for="view.name">{{ view.title }}</label></p>
  </div>
  <div v-else-if="mode === 'link'">
    <div class="label checkbox"><i class="fa fa-check-square"></i><span>{{ view.title }}</span></div>
  </div>
  <div v-else-if="mode === 'edit'">
    <label>{{ view.title }}:</label><span :name="view.name" :label="view.title" class="error"></span><br>
    <input type="text" :name="view.name" v-model="view.value" :disabled="view.readonly" :placeholder="view.title">
  </div>
  <div v-else-if="mode === 'search'">
    <div class="label checkbox"><i class="fa fa-check-square"></i><span>{{ view.title }}</span></div>
    <div>
      <select>
        <option value="2">Не важно</option>
        <option value="1">Да</option>
        <option value="1">Нет</option>
      </select>
    </div>
  </div>
</template>

<script>
export default {
  name: 'checkbox-property',
  props: ['className', 'mode', 'view', 'model'],
  data () {
    return {
      value: 2
    }
  },
  mounted () {
    this.update(this.view.value)
  },
  methods: {
    update (value) {
      this.$emit('update', {value: value})
    },
    switchValue () {
      this.value = this.value - 1

      if (this.value < 0) {
        this.value = 2
      }
    }
  }
}
</script>

<style scoped>
.false {
  color: #999;
}
</style>
