// src/components/properties/float-property/float-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'float-property',
  templateUrl: './float-property.component.html',
  styleUrls: ['./float-property.component.css']
})
export class FloatPropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;

  constructor() { }

  ngOnInit() {
  }

}

<div *ngIf="mode == 'edit'">
    <label>{{view.title}}:</label><span attr.name="{{view.name}}" class="error"></span><br>
    <input type="text" name="{{view.name}}" [(ngModel)]="model[view.name].value" [disabled]="view.readonly" placeholder="{{view.title}}" class="number">
</div>
<div *ngIf="mode == 'browse'">
    {{view.value}}
</div>
<div *ngIf="mode == 'link'">
    <div class="label number"><span class="glyphicons glyphicons-calculator"></span><span>{{view.title}}</span></div>
</div>
<div *ngIf="mode == 'search'">
    <div class="label number"><span class="glyphicons glyphicons-calculator"></span><span>{{view.title}}</span></div>
    <div><input type="text" value="{{view.value}}" placeholder="" class="number"></div>
</div>

// src/components/properties/FloatProperty.vue
<template>
  <div v-if="mode === 'browse'">
    <div v-html="view.value"></div>
  </div>
  <div v-else-if="mode === 'edit'">
    <label>{{ view.title }}:</label><span :name="view.name" :label="view.title" class="error"></span><br>
    <input type="text" class="number" :name="view.name" v-on:input="update($event.target.value)" :value="view.value" :disabled="view.readonly" :placeholder="view.title">
  </div>
  <div v-else-if="mode === 'link'">
    <div class="label number"><i class="fa fa-calculator"></i><span>{{ view.title }}</span></div>
  </div>
  <div v-else-if="mode === 'search'">
    <div class="label number"><i class="fa fa-calculator"></i><span>{{ view.title }}</span></div>
    <div>
      <input type="text" class="number" :value="view.value" placeholder="От"> &mdash;
      <input type="text" class="number" :value="view.value" placeholder="До">
    </div>
  </div>
</template>

<script>
export default {
  name: 'textfield-property',
  props: ['className', 'mode', 'view', 'model'],
  mounted () {
    this.update(this.view.value)
  },
  methods: {
    update (value) {
      this.$emit('update', {value: value})
    }
  }
}
</script>

<style scoped>
input[type="text"].number {
  width: 5rem;
}
</style>
