// src/components/properties/textfield-property/textfield-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Http, Response } from '@angular/http';
import { HttpService } from '../../http.service';

declare var jQuery:any;

@Component({
  selector: 'textfield-property',
  templateUrl: './textfield-property.component.html',
  styleUrls: ['./textfield-property.component.css']
})
export class TextfieldPropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;

  value = null;

  constructor(
    public http: HttpService
  ) { }

  ngOnInit() {
    if (this.view.isMainProperty) {
      this.model[this.view.name] = {
        value: (this.view.value ? this.view.value.id : null)
      };
    }
  }

  ngAfterViewInit() {
    if (this.view.isMainProperty) {
      let loggedUser = JSON.parse(localStorage.getItem('loggedUser'));
      let token = loggedUser && loggedUser.token;
      let self = this;

      jQuery('#'+this.view.name+'_autocomplete').autocomplete({
        serviceUrl: this.http.url('/elements/autocomplete'),
        ajaxSettings: {
          headers: this.http.authHeader()
        },
        params: {
          item: this.view.relatedClass
        },
        onSelect: function (suggestion) {
          self.model[self.view.name].value = suggestion.id;
          self.value = suggestion.value;
          self.view.value = {
            name: suggestion.value,
            classId: suggestion.classId
          };
        },
        appendTo: jQuery('span.autocomplete-container[name="'+this.view.name+'_auto"]'),
        maxHeight: 400,
        minChars: 0
      });
    }
  }

  reset() {
    this.view.value = null;
    this.model[this.view.name].value = null;
    this.value = null;
  }

}
<div *ngIf="mode == 'edit'">
    <label>{{view.title}}:</label><span attr.name="{{view.name}}" class="error"></span><br>
    <input type="text" name="{{view.name}}" [(ngModel)]="model[view.name].value" [disabled]="view.readonly" placeholder="{{view.title}}">
</div>
<div *ngIf="mode == 'browse'">
    {{view.value}}
</div>
<div *ngIf="mode == 'link'">
    <div *ngIf="view.isMainProperty" class="label main"><span class="glyphicons glyphicons-flag"></span><span>ID или название</span></div>
    <div *ngIf=" ! view.isMainProperty" class="label textfield"><span class="glyphicons glyphicons-pencil"></span><span>{{view.title}}</span></div>
</div>
<div *ngIf="mode == 'search'">
    <div *ngIf="view.isMainProperty">
        <div class="label main"><span class="glyphicons glyphicons-flag"></span><span>{{view.title}}</span></div>
        <div>
            <input type="text" name="{{view.name}}" id="{{view.name}}_autocomplete" [(ngModel)]="value" placeholder="ID или название">
            <span attr.name="{{view.name}}_auto" class="autocomplete-container"></span>
            <span attr.name="{{view.name}}" class="reset" (click)="reset()">&#215;</span>
        </div>
    </div>
    <div *ngIf=" ! view.isMainProperty">
        <div class="label textfield"><span class="glyphicons glyphicons-pencil"></span><span>{{view.title}}</span></div>
        <div><input type="text" value="{{view.value}}" placeholder=""></div>
    </div>
</div>

// src/components/properties/TextfieldProperty.vue
<template>
  <div v-if="mode === 'browse'">
    <div v-html="view.value"></div>
  </div>
  <div v-else-if="mode === 'edit'">
    <label>{{ view.title }}:</label><span :name="view.name" :label="view.title" class="error"></span><br>
    <input type="text" :class="{mainp: view.isMainProperty}" :name="view.name" v-on:input="update($event.target.value)" :value="view.value" :disabled="view.readonly" :placeholder="view.title">
  </div>
  <div v-else-if="mode === 'link'">
    <div v-if="view.isMainProperty" class="label mainp"><i class="fa fa-flag"></i><span>ID или название</span></div>
    <div v-else class="label textfield"><i class="fa fa-pencil"></i><span>{{ view.title }}</span></div>
  </div>
  <div v-else-if="mode === 'search'">
    <div v-if="view.isMainProperty" class="label mainp"><i class="fa fa-flag"></i><span>ID или название</span></div>
    <div v-else class="label textfield"><i class="fa fa-pencil"></i><span>{{ view.title }}</span></div>
    <div><input type="text" :value="view.value" placeholder=""></div>
  </div>
</template>

<script>
export default {
  name: 'textfield-property',
  props: ['className', 'mode', 'view', 'model'],
  mounted () {
    this.update(this.view.value)
  },
  methods: {
    update (value) {
      this.$emit('update', {value: value})
    }
  }
}
</script>

<style scoped>
input[type="text"].mainp {
  width: 30rem;
  height: 3rem;
  color: steelblue;
  font-size: 1.2rem;
}
</style>
