// src/components/properties/virtual-property/virtual-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'virtual-property',
  templateUrl: './virtual-property.component.html',
  styleUrls: ['./virtual-property.component.css']
})
export class VirtualPropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;

  constructor() { }

  ngOnInit() {
  }

}

<div *ngIf="mode == 'edit'">
    <label>{{view.title}}:</label><br>
    <div [innerHTML]="view.value"></div>
</div>
<div *ngIf="mode == 'browse'">
    <div [innerHTML]="view.value"></div>
</div>

// src/components/properties/VirtualProperty.vue
<template>
  <div v-if="mode === 'browse'">
    <div v-html="view.value"></div>
  </div>
  <div v-else-if="mode === 'edit'">
    <label>{{ view.title }}:</label><br>
    <div v-html="view.value"></div>
  </div>
</template>

<script>
export default {
  name: 'virtual-property',
  props: ['className', 'mode', 'view', 'model']
}
</script>
