// src/components/properties/OnetooneProperty.vue
<template>
  <div v-if="mode === 'browse'">
    <div v-if="view.value"><a>{{ view.value.name }}</a></div>
    <div v-else class="undefined">Не определено</div>
  </div>
  <div v-else-if="mode === 'edit'">
    <label>{{ view.title }}:</label>
    <span v-if="element">
      <router-link :to="{name: 'browse', params: {classId: element.classId}, query: {mode: 'edit'}}">{{ element.name }}</router-link>
    </span>
    <span v-else>
      Не определено
    </span>
    <span :name="view.name" :label="view.title" class="error"></span><br>
    <autocomplete :name="view.name" :value="initial" :item="view.relatedClass" v-on:update="update(arguments[0])" placeholder="ID или название"></autocomplete>
    <span class="reset" @click="reset()">&#215;</span>
  </div>
  <div v-else-if="mode === 'link'">
    <div class="label one"><i class="fa fa-tag"></i><span>{{ view.title }}</span></div>
  </div>
  <div v-else-if="mode === 'search'">
    <div class="label one"><i class="fa fa-tag"></i><span>{{ view.title }}</span></div>
    <div><input type="text" :value="view.value" placeholder="ID или название"></div>
  </div>
</template>

<script>
import Autocomplete from '../common/Autocomplete'

export default {
  name: 'onetoone-property',
  components: {
    Autocomplete
  },
  props: ['className', 'mode', 'view'],
  watch: {
    view (to, from) {
      this.initial = null
    }
  },
  data () {
    return {
      initial: null,
      element: this.view.value
    }
  },
  mounted () {
    let value = this.element ? this.element.id : null

    this.$emit('update', {value: value})
  },
  methods: {
    update (value) {
      this.element = value ? {
        id: value.id,
        classId: value.classId,
        name: value.value
      } : null

      this.initial = value ? value.value : null

      value = this.element ? this.element.id : null

      this.$emit('update', {value: value})
    },
    reset () {
      this.element = null
      this.initial = null

      this.$emit('update', {value: null})
    }
  }
}
</script>

<style scoped>
.undefined {
  color: #999;
}
</style>

// src/components/properties/onetoone-property/onetoone-property.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Http, Response } from '@angular/http';
import { HttpService } from '../../http.service';

declare var jQuery:any;

@Component({
  selector: 'onetoone-property',
  templateUrl: './onetoone-property.component.html',
  styleUrls: ['./onetoone-property.component.css']
})
export class OnetoonePropertyComponent implements OnInit {

  @Input() mode: string;
  @Input() view: any;
  @Input() model: any;

  value = null;

  constructor(
    public http: HttpService
  ) { }

  ngOnInit() {
    this.model[this.view.name] = {
      value: (this.view.value ? this.view.value.id : null)
    };
  }

  ngAfterViewInit() {
    let self = this;

    console.log(this.view.name);

    jQuery('#'+this.view.name+'_autocomplete').autocomplete({
      serviceUrl: this.http.url('/elements/autocomplete'),
      ajaxSettings: {
        headers: this.http.authHeader()
      },
      params: {
        item: this.view.relatedClass
      },
      onSelect: function (suggestion) {
        self.model[self.view.name].value = suggestion.id;
        self.value = suggestion.value;
        self.view.value = {
          name: suggestion.value,
          classId: suggestion.classId
        };
      },
      appendTo: jQuery('span.autocomplete-container[name="'+this.view.name+'_auto"]'),
      maxHeight: 400,
      minChars: 0
    });
  }

  reset() {
    this.view.value = null;
    this.model[this.view.name].value = null;
    this.value = null;
  }
}

<div *ngIf="mode == 'edit'">
    <label>{{view.title}}:</label>
    <span *ngIf="view.value" attr.name="{{view.name}}" class="container">
        <a [routerLink]="['/browse/', view.value.classId, {mode: 'edit'}]">{{view.value.name}}</a>
    </span>
    <span *ngIf=" ! view.value" attr.name="{{view.name}}" class="container">
        Не определено
    </span>
    <div *ngIf=" ! view.readonly">
        <input type="text" name="{{view.name}}" id="{{view.name}}_autocomplete" [(ngModel)]="value" placeholder="ID или название">
        <span attr.name="{{view.name}}_auto" class="autocomplete-container"></span>
        <span attr.name="{{view.name}}" class="reset" (click)="reset()">&#215;</span>
    </div>
</div>
<div *ngIf="mode == 'browse'">
    <span *ngIf="view.value">
        <a [routerLink]="['/browse/', view.value.classId, {mode: 'edit'}]">{{view.value.name}}</a>
    </span>
</div>
<div *ngIf="mode == 'link'">
    <div class="label one"><span class="glyphicons glyphicons-tag"></span><span>{{view.title}}</span></div>
</div>
<div *ngIf="mode == 'search'">
    <div class="label one">
        <span class="glyphicons glyphicons-tag"></span><span>{{view.title}}:</span>
    </div>
    <div>
        <input type="text" name="{{view.name}}" id="{{view.name}}_autocomplete" [(ngModel)]="value" placeholder="ID или название">
        <span attr.name="{{view.name}}_auto" class="autocomplete-container"></span>
        <span attr.name="{{view.name}}" class="reset" (click)="reset()">&#215;</span>
    </div>
</div>
